# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'CDAGUI.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1440, 792)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.sendsirial_1 = QtWidgets.QPushButton(self.centralwidget)
        self.sendsirial_1.setGeometry(QtCore.QRect(30, 200, 91, 41))
        self.sendsirial_1.setObjectName("sendsirial_1")
        self.layoutWidget_9 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget_9.setGeometry(QtCore.QRect(230, 180, 481, 58))
        self.layoutWidget_9.setObjectName("layoutWidget_9")
        self.sliderrange_1 = QtWidgets.QVBoxLayout(self.layoutWidget_9)
        self.sliderrange_1.setContentsMargins(0, 0, 0, 0)
        self.sliderrange_1.setObjectName("sliderrange_1")
        self.starttime_1 = QtWidgets.QSlider(self.layoutWidget_9)
        self.starttime_1.setMaximum(150)
        self.starttime_1.setOrientation(QtCore.Qt.Horizontal)
        self.starttime_1.setObjectName("starttime_1")
        self.sliderrange_1.addWidget(self.starttime_1)
        self.endtime_1 = QtWidgets.QSlider(self.layoutWidget_9)
        self.endtime_1.setMaximum(150)
        self.endtime_1.setSingleStep(3)
        self.endtime_1.setPageStep(9)
        self.endtime_1.setOrientation(QtCore.Qt.Horizontal)
        self.endtime_1.setObjectName("endtime_1")
        self.sliderrange_1.addWidget(self.endtime_1)
        self.portnum_1 = QtWidgets.QLabel(self.centralwidget)
        self.portnum_1.setGeometry(QtCore.QRect(40, 170, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.portnum_1.setFont(font)
        self.portnum_1.setObjectName("portnum_1")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(140, 190, 81, 18))
        self.layoutWidget.setObjectName("layoutWidget")
        self.numrange_1 = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.numrange_1.setContentsMargins(0, 0, 0, 0)
        self.numrange_1.setObjectName("numrange_1")
        self.startnum_1 = QtWidgets.QLabel(self.layoutWidget)
        self.startnum_1.setObjectName("startnum_1")
        self.numrange_1.addWidget(self.startnum_1)
        self.tilde_1 = QtWidgets.QLabel(self.layoutWidget)
        self.tilde_1.setObjectName("tilde_1")
        self.numrange_1.addWidget(self.tilde_1)
        self.endnum_1 = QtWidgets.QLabel(self.layoutWidget)
        self.endnum_1.setObjectName("endnum_1")
        self.numrange_1.addWidget(self.endnum_1)
        self.msec_1 = QtWidgets.QLabel(self.centralwidget)
        self.msec_1.setGeometry(QtCore.QRect(190, 210, 33, 16))
        self.msec_1.setObjectName("msec_1")
        self.sendsirial_2 = QtWidgets.QPushButton(self.centralwidget)
        self.sendsirial_2.setGeometry(QtCore.QRect(30, 320, 91, 41))
        self.sendsirial_2.setObjectName("sendsirial_2")
        self.layoutWidget_10 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget_10.setGeometry(QtCore.QRect(230, 300, 481, 58))
        self.layoutWidget_10.setObjectName("layoutWidget_10")
        self.sliderrange_2 = QtWidgets.QVBoxLayout(self.layoutWidget_10)
        self.sliderrange_2.setContentsMargins(0, 0, 0, 0)
        self.sliderrange_2.setObjectName("sliderrange_2")
        self.starttime_2 = QtWidgets.QSlider(self.layoutWidget_10)
        self.starttime_2.setMaximum(150)
        self.starttime_2.setOrientation(QtCore.Qt.Horizontal)
        self.starttime_2.setObjectName("starttime_2")
        self.sliderrange_2.addWidget(self.starttime_2)
        self.endtime_2 = QtWidgets.QSlider(self.layoutWidget_10)
        self.endtime_2.setMaximum(150)
        self.endtime_2.setSingleStep(3)
        self.endtime_2.setPageStep(9)
        self.endtime_2.setOrientation(QtCore.Qt.Horizontal)
        self.endtime_2.setObjectName("endtime_2")
        self.sliderrange_2.addWidget(self.endtime_2)
        self.portnum_2 = QtWidgets.QLabel(self.centralwidget)
        self.portnum_2.setGeometry(QtCore.QRect(40, 290, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.portnum_2.setFont(font)
        self.portnum_2.setObjectName("portnum_2")
        self.layoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget_2.setGeometry(QtCore.QRect(140, 310, 81, 18))
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        self.numrange_2 = QtWidgets.QHBoxLayout(self.layoutWidget_2)
        self.numrange_2.setContentsMargins(0, 0, 0, 0)
        self.numrange_2.setObjectName("numrange_2")
        self.startnum_2 = QtWidgets.QLabel(self.layoutWidget_2)
        self.startnum_2.setObjectName("startnum_2")
        self.numrange_2.addWidget(self.startnum_2)
        self.tilde_2 = QtWidgets.QLabel(self.layoutWidget_2)
        self.tilde_2.setObjectName("tilde_2")
        self.numrange_2.addWidget(self.tilde_2)
        self.endnum_2 = QtWidgets.QLabel(self.layoutWidget_2)
        self.endnum_2.setObjectName("endnum_2")
        self.numrange_2.addWidget(self.endnum_2)
        self.msec_2 = QtWidgets.QLabel(self.centralwidget)
        self.msec_2.setGeometry(QtCore.QRect(190, 330, 33, 16))
        self.msec_2.setObjectName("msec_2")
        self.FIREbutton = QtWidgets.QPushButton(self.centralwidget)
        self.FIREbutton.setGeometry(QtCore.QRect(480, 30, 521, 121))
        font = QtGui.QFont()
        font.setFamily("Courier")
        font.setPointSize(96)
        font.setItalic(False)
        self.FIREbutton.setFont(font)
        self.FIREbutton.setObjectName("FIREbutton")
        self.portnum_3 = QtWidgets.QLabel(self.centralwidget)
        self.portnum_3.setGeometry(QtCore.QRect(40, 410, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.portnum_3.setFont(font)
        self.portnum_3.setObjectName("portnum_3")
        self.layoutWidget_3 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget_3.setGeometry(QtCore.QRect(140, 430, 81, 18))
        self.layoutWidget_3.setObjectName("layoutWidget_3")
        self.numrange_3 = QtWidgets.QHBoxLayout(self.layoutWidget_3)
        self.numrange_3.setContentsMargins(0, 0, 0, 0)
        self.numrange_3.setObjectName("numrange_3")
        self.startnum_3 = QtWidgets.QLabel(self.layoutWidget_3)
        self.startnum_3.setObjectName("startnum_3")
        self.numrange_3.addWidget(self.startnum_3)
        self.tilde_3 = QtWidgets.QLabel(self.layoutWidget_3)
        self.tilde_3.setObjectName("tilde_3")
        self.numrange_3.addWidget(self.tilde_3)
        self.endnum_3 = QtWidgets.QLabel(self.layoutWidget_3)
        self.endnum_3.setObjectName("endnum_3")
        self.numrange_3.addWidget(self.endnum_3)
        self.msec_3 = QtWidgets.QLabel(self.centralwidget)
        self.msec_3.setGeometry(QtCore.QRect(190, 450, 33, 16))
        self.msec_3.setObjectName("msec_3")
        self.layoutWidget_11 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget_11.setGeometry(QtCore.QRect(230, 420, 481, 58))
        self.layoutWidget_11.setObjectName("layoutWidget_11")
        self.sliderrange_3 = QtWidgets.QVBoxLayout(self.layoutWidget_11)
        self.sliderrange_3.setContentsMargins(0, 0, 0, 0)
        self.sliderrange_3.setObjectName("sliderrange_3")
        self.starttime_3 = QtWidgets.QSlider(self.layoutWidget_11)
        self.starttime_3.setMaximum(150)
        self.starttime_3.setOrientation(QtCore.Qt.Horizontal)
        self.starttime_3.setObjectName("starttime_3")
        self.sliderrange_3.addWidget(self.starttime_3)
        self.endtime_3 = QtWidgets.QSlider(self.layoutWidget_11)
        self.endtime_3.setMaximum(150)
        self.endtime_3.setSingleStep(3)
        self.endtime_3.setPageStep(9)
        self.endtime_3.setOrientation(QtCore.Qt.Horizontal)
        self.endtime_3.setObjectName("endtime_3")
        self.sliderrange_3.addWidget(self.endtime_3)
        self.sendsirial_3 = QtWidgets.QPushButton(self.centralwidget)
        self.sendsirial_3.setGeometry(QtCore.QRect(30, 440, 91, 41))
        self.sendsirial_3.setObjectName("sendsirial_3")
        self.portnum_4 = QtWidgets.QLabel(self.centralwidget)
        self.portnum_4.setGeometry(QtCore.QRect(40, 530, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.portnum_4.setFont(font)
        self.portnum_4.setObjectName("portnum_4")
        self.layoutWidget_4 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget_4.setGeometry(QtCore.QRect(140, 550, 81, 18))
        self.layoutWidget_4.setObjectName("layoutWidget_4")
        self.numrange_4 = QtWidgets.QHBoxLayout(self.layoutWidget_4)
        self.numrange_4.setContentsMargins(0, 0, 0, 0)
        self.numrange_4.setObjectName("numrange_4")
        self.startnum_4 = QtWidgets.QLabel(self.layoutWidget_4)
        self.startnum_4.setObjectName("startnum_4")
        self.numrange_4.addWidget(self.startnum_4)
        self.tilde_4 = QtWidgets.QLabel(self.layoutWidget_4)
        self.tilde_4.setObjectName("tilde_4")
        self.numrange_4.addWidget(self.tilde_4)
        self.endnum_4 = QtWidgets.QLabel(self.layoutWidget_4)
        self.endnum_4.setObjectName("endnum_4")
        self.numrange_4.addWidget(self.endnum_4)
        self.msec_4 = QtWidgets.QLabel(self.centralwidget)
        self.msec_4.setGeometry(QtCore.QRect(190, 570, 33, 16))
        self.msec_4.setObjectName("msec_4")
        self.layoutWidget_12 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget_12.setGeometry(QtCore.QRect(230, 540, 481, 58))
        self.layoutWidget_12.setObjectName("layoutWidget_12")
        self.sliderrange_4 = QtWidgets.QVBoxLayout(self.layoutWidget_12)
        self.sliderrange_4.setContentsMargins(0, 0, 0, 0)
        self.sliderrange_4.setObjectName("sliderrange_4")
        self.starttime_4 = QtWidgets.QSlider(self.layoutWidget_12)
        self.starttime_4.setMaximum(150)
        self.starttime_4.setOrientation(QtCore.Qt.Horizontal)
        self.starttime_4.setObjectName("starttime_4")
        self.sliderrange_4.addWidget(self.starttime_4)
        self.endtime_4 = QtWidgets.QSlider(self.layoutWidget_12)
        self.endtime_4.setMaximum(150)
        self.endtime_4.setSingleStep(3)
        self.endtime_4.setPageStep(9)
        self.endtime_4.setOrientation(QtCore.Qt.Horizontal)
        self.endtime_4.setObjectName("endtime_4")
        self.sliderrange_4.addWidget(self.endtime_4)
        self.sendsirial_4 = QtWidgets.QPushButton(self.centralwidget)
        self.sendsirial_4.setGeometry(QtCore.QRect(30, 560, 91, 41))
        self.sendsirial_4.setObjectName("sendsirial_4")
        self.portnum_5 = QtWidgets.QLabel(self.centralwidget)
        self.portnum_5.setGeometry(QtCore.QRect(40, 650, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.portnum_5.setFont(font)
        self.portnum_5.setObjectName("portnum_5")
        self.layoutWidget_5 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget_5.setGeometry(QtCore.QRect(140, 670, 81, 18))
        self.layoutWidget_5.setObjectName("layoutWidget_5")
        self.numrange_5 = QtWidgets.QHBoxLayout(self.layoutWidget_5)
        self.numrange_5.setContentsMargins(0, 0, 0, 0)
        self.numrange_5.setObjectName("numrange_5")
        self.startnum_5 = QtWidgets.QLabel(self.layoutWidget_5)
        self.startnum_5.setObjectName("startnum_5")
        self.numrange_5.addWidget(self.startnum_5)
        self.tilde_5 = QtWidgets.QLabel(self.layoutWidget_5)
        self.tilde_5.setObjectName("tilde_5")
        self.numrange_5.addWidget(self.tilde_5)
        self.endnum_5 = QtWidgets.QLabel(self.layoutWidget_5)
        self.endnum_5.setObjectName("endnum_5")
        self.numrange_5.addWidget(self.endnum_5)
        self.msec_5 = QtWidgets.QLabel(self.centralwidget)
        self.msec_5.setGeometry(QtCore.QRect(190, 690, 33, 16))
        self.msec_5.setObjectName("msec_5")
        self.layoutWidget_13 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget_13.setGeometry(QtCore.QRect(230, 660, 481, 58))
        self.layoutWidget_13.setObjectName("layoutWidget_13")
        self.sliderrange_5 = QtWidgets.QVBoxLayout(self.layoutWidget_13)
        self.sliderrange_5.setContentsMargins(0, 0, 0, 0)
        self.sliderrange_5.setObjectName("sliderrange_5")
        self.starttime_5 = QtWidgets.QSlider(self.layoutWidget_13)
        self.starttime_5.setMaximum(150)
        self.starttime_5.setOrientation(QtCore.Qt.Horizontal)
        self.starttime_5.setObjectName("starttime_5")
        self.sliderrange_5.addWidget(self.starttime_5)
        self.endtime_5 = QtWidgets.QSlider(self.layoutWidget_13)
        self.endtime_5.setMaximum(150)
        self.endtime_5.setSingleStep(3)
        self.endtime_5.setPageStep(9)
        self.endtime_5.setOrientation(QtCore.Qt.Horizontal)
        self.endtime_5.setObjectName("endtime_5")
        self.sliderrange_5.addWidget(self.endtime_5)
        self.sendsirial_5 = QtWidgets.QPushButton(self.centralwidget)
        self.sendsirial_5.setGeometry(QtCore.QRect(30, 680, 91, 41))
        self.sendsirial_5.setObjectName("sendsirial_5")
        self.portnum_6 = QtWidgets.QLabel(self.centralwidget)
        self.portnum_6.setGeometry(QtCore.QRect(740, 170, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.portnum_6.setFont(font)
        self.portnum_6.setObjectName("portnum_6")
        self.layoutWidget_6 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget_6.setGeometry(QtCore.QRect(840, 190, 81, 18))
        self.layoutWidget_6.setObjectName("layoutWidget_6")
        self.numrange_6 = QtWidgets.QHBoxLayout(self.layoutWidget_6)
        self.numrange_6.setContentsMargins(0, 0, 0, 0)
        self.numrange_6.setObjectName("numrange_6")
        self.startnum_6 = QtWidgets.QLabel(self.layoutWidget_6)
        self.startnum_6.setObjectName("startnum_6")
        self.numrange_6.addWidget(self.startnum_6)
        self.tilde_6 = QtWidgets.QLabel(self.layoutWidget_6)
        self.tilde_6.setObjectName("tilde_6")
        self.numrange_6.addWidget(self.tilde_6)
        self.endnum_6 = QtWidgets.QLabel(self.layoutWidget_6)
        self.endnum_6.setObjectName("endnum_6")
        self.numrange_6.addWidget(self.endnum_6)
        self.msec_6 = QtWidgets.QLabel(self.centralwidget)
        self.msec_6.setGeometry(QtCore.QRect(890, 210, 33, 16))
        self.msec_6.setObjectName("msec_6")
        self.layoutWidget_14 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget_14.setGeometry(QtCore.QRect(930, 180, 481, 58))
        self.layoutWidget_14.setObjectName("layoutWidget_14")
        self.sliderrange_6 = QtWidgets.QVBoxLayout(self.layoutWidget_14)
        self.sliderrange_6.setContentsMargins(0, 0, 0, 0)
        self.sliderrange_6.setObjectName("sliderrange_6")
        self.starttime_6 = QtWidgets.QSlider(self.layoutWidget_14)
        self.starttime_6.setMaximum(150)
        self.starttime_6.setOrientation(QtCore.Qt.Horizontal)
        self.starttime_6.setObjectName("starttime_6")
        self.sliderrange_6.addWidget(self.starttime_6)
        self.endtime_6 = QtWidgets.QSlider(self.layoutWidget_14)
        self.endtime_6.setMaximum(150)
        self.endtime_6.setSingleStep(3)
        self.endtime_6.setPageStep(9)
        self.endtime_6.setOrientation(QtCore.Qt.Horizontal)
        self.endtime_6.setObjectName("endtime_6")
        self.sliderrange_6.addWidget(self.endtime_6)
        self.sendsirial_6 = QtWidgets.QPushButton(self.centralwidget)
        self.sendsirial_6.setGeometry(QtCore.QRect(730, 200, 91, 41))
        self.sendsirial_6.setObjectName("sendsirial_6")
        self.portnum_7 = QtWidgets.QLabel(self.centralwidget)
        self.portnum_7.setGeometry(QtCore.QRect(740, 290, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.portnum_7.setFont(font)
        self.portnum_7.setObjectName("portnum_7")
        self.layoutWidget_7 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget_7.setGeometry(QtCore.QRect(840, 310, 81, 18))
        self.layoutWidget_7.setObjectName("layoutWidget_7")
        self.numrange_7 = QtWidgets.QHBoxLayout(self.layoutWidget_7)
        self.numrange_7.setContentsMargins(0, 0, 0, 0)
        self.numrange_7.setObjectName("numrange_7")
        self.startnum_7 = QtWidgets.QLabel(self.layoutWidget_7)
        self.startnum_7.setObjectName("startnum_7")
        self.numrange_7.addWidget(self.startnum_7)
        self.tilde_7 = QtWidgets.QLabel(self.layoutWidget_7)
        self.tilde_7.setObjectName("tilde_7")
        self.numrange_7.addWidget(self.tilde_7)
        self.endnum_7 = QtWidgets.QLabel(self.layoutWidget_7)
        self.endnum_7.setObjectName("endnum_7")
        self.numrange_7.addWidget(self.endnum_7)
        self.msec_7 = QtWidgets.QLabel(self.centralwidget)
        self.msec_7.setGeometry(QtCore.QRect(890, 330, 33, 16))
        self.msec_7.setObjectName("msec_7")
        self.layoutWidget_15 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget_15.setGeometry(QtCore.QRect(930, 300, 481, 58))
        self.layoutWidget_15.setObjectName("layoutWidget_15")
        self.sliderrange_7 = QtWidgets.QVBoxLayout(self.layoutWidget_15)
        self.sliderrange_7.setContentsMargins(0, 0, 0, 0)
        self.sliderrange_7.setObjectName("sliderrange_7")
        self.starttime_7 = QtWidgets.QSlider(self.layoutWidget_15)
        self.starttime_7.setMaximum(150)
        self.starttime_7.setOrientation(QtCore.Qt.Horizontal)
        self.starttime_7.setObjectName("starttime_7")
        self.sliderrange_7.addWidget(self.starttime_7)
        self.endtime_7 = QtWidgets.QSlider(self.layoutWidget_15)
        self.endtime_7.setMaximum(150)
        self.endtime_7.setSingleStep(3)
        self.endtime_7.setPageStep(9)
        self.endtime_7.setOrientation(QtCore.Qt.Horizontal)
        self.endtime_7.setObjectName("endtime_7")
        self.sliderrange_7.addWidget(self.endtime_7)
        self.sendsirial_7 = QtWidgets.QPushButton(self.centralwidget)
        self.sendsirial_7.setGeometry(QtCore.QRect(730, 320, 91, 41))
        self.sendsirial_7.setObjectName("sendsirial_7")
        self.portnum_8 = QtWidgets.QLabel(self.centralwidget)
        self.portnum_8.setGeometry(QtCore.QRect(740, 410, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.portnum_8.setFont(font)
        self.portnum_8.setObjectName("portnum_8")
        self.layoutWidget_8 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget_8.setGeometry(QtCore.QRect(840, 430, 81, 18))
        self.layoutWidget_8.setObjectName("layoutWidget_8")
        self.numrange_8 = QtWidgets.QHBoxLayout(self.layoutWidget_8)
        self.numrange_8.setContentsMargins(0, 0, 0, 0)
        self.numrange_8.setObjectName("numrange_8")
        self.startnum_8 = QtWidgets.QLabel(self.layoutWidget_8)
        self.startnum_8.setObjectName("startnum_8")
        self.numrange_8.addWidget(self.startnum_8)
        self.tilde_8 = QtWidgets.QLabel(self.layoutWidget_8)
        self.tilde_8.setObjectName("tilde_8")
        self.numrange_8.addWidget(self.tilde_8)
        self.endnum_8 = QtWidgets.QLabel(self.layoutWidget_8)
        self.endnum_8.setObjectName("endnum_8")
        self.numrange_8.addWidget(self.endnum_8)
        self.msec_8 = QtWidgets.QLabel(self.centralwidget)
        self.msec_8.setGeometry(QtCore.QRect(890, 450, 33, 16))
        self.msec_8.setObjectName("msec_8")
        self.layoutWidget_16 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget_16.setGeometry(QtCore.QRect(930, 420, 481, 58))
        self.layoutWidget_16.setObjectName("layoutWidget_16")
        self.sliderrange_8 = QtWidgets.QVBoxLayout(self.layoutWidget_16)
        self.sliderrange_8.setContentsMargins(0, 0, 0, 0)
        self.sliderrange_8.setObjectName("sliderrange_8")
        self.starttime_8 = QtWidgets.QSlider(self.layoutWidget_16)
        self.starttime_8.setMaximum(150)
        self.starttime_8.setOrientation(QtCore.Qt.Horizontal)
        self.starttime_8.setObjectName("starttime_8")
        self.sliderrange_8.addWidget(self.starttime_8)
        self.endtime_8 = QtWidgets.QSlider(self.layoutWidget_16)
        self.endtime_8.setMaximum(150)
        self.endtime_8.setSingleStep(3)
        self.endtime_8.setPageStep(9)
        self.endtime_8.setOrientation(QtCore.Qt.Horizontal)
        self.endtime_8.setObjectName("endtime_8")
        self.sliderrange_8.addWidget(self.endtime_8)
        self.sendsirial_8 = QtWidgets.QPushButton(self.centralwidget)
        self.sendsirial_8.setGeometry(QtCore.QRect(730, 440, 91, 41))
        self.sendsirial_8.setObjectName("sendsirial_8")
        self.portnum_9 = QtWidgets.QLabel(self.centralwidget)
        self.portnum_9.setGeometry(QtCore.QRect(740, 530, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.portnum_9.setFont(font)
        self.portnum_9.setObjectName("portnum_9")
        self.layoutWidget_17 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget_17.setGeometry(QtCore.QRect(840, 550, 81, 18))
        self.layoutWidget_17.setObjectName("layoutWidget_17")
        self.numrange_9 = QtWidgets.QHBoxLayout(self.layoutWidget_17)
        self.numrange_9.setContentsMargins(0, 0, 0, 0)
        self.numrange_9.setObjectName("numrange_9")
        self.startnum_9 = QtWidgets.QLabel(self.layoutWidget_17)
        self.startnum_9.setObjectName("startnum_9")
        self.numrange_9.addWidget(self.startnum_9)
        self.tilde_9 = QtWidgets.QLabel(self.layoutWidget_17)
        self.tilde_9.setObjectName("tilde_9")
        self.numrange_9.addWidget(self.tilde_9)
        self.endnum_9 = QtWidgets.QLabel(self.layoutWidget_17)
        self.endnum_9.setObjectName("endnum_9")
        self.numrange_9.addWidget(self.endnum_9)
        self.msec_9 = QtWidgets.QLabel(self.centralwidget)
        self.msec_9.setGeometry(QtCore.QRect(890, 570, 33, 16))
        self.msec_9.setObjectName("msec_9")
        self.layoutWidget_18 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget_18.setGeometry(QtCore.QRect(930, 540, 481, 58))
        self.layoutWidget_18.setObjectName("layoutWidget_18")
        self.sliderrange_9 = QtWidgets.QVBoxLayout(self.layoutWidget_18)
        self.sliderrange_9.setContentsMargins(0, 0, 0, 0)
        self.sliderrange_9.setObjectName("sliderrange_9")
        self.starttime_9 = QtWidgets.QSlider(self.layoutWidget_18)
        self.starttime_9.setMaximum(150)
        self.starttime_9.setOrientation(QtCore.Qt.Horizontal)
        self.starttime_9.setObjectName("starttime_9")
        self.sliderrange_9.addWidget(self.starttime_9)
        self.endtime_9 = QtWidgets.QSlider(self.layoutWidget_18)
        self.endtime_9.setMaximum(150)
        self.endtime_9.setSingleStep(3)
        self.endtime_9.setPageStep(9)
        self.endtime_9.setOrientation(QtCore.Qt.Horizontal)
        self.endtime_9.setObjectName("endtime_9")
        self.sliderrange_9.addWidget(self.endtime_9)
        self.sendsirial_9 = QtWidgets.QPushButton(self.centralwidget)
        self.sendsirial_9.setGeometry(QtCore.QRect(730, 560, 91, 41))
        self.sendsirial_9.setObjectName("sendsirial_9")
        self.portnum_10 = QtWidgets.QLabel(self.centralwidget)
        self.portnum_10.setGeometry(QtCore.QRect(740, 650, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.portnum_10.setFont(font)
        self.portnum_10.setObjectName("portnum_10")
        self.layoutWidget_19 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget_19.setGeometry(QtCore.QRect(840, 670, 81, 18))
        self.layoutWidget_19.setObjectName("layoutWidget_19")
        self.numrange_10 = QtWidgets.QHBoxLayout(self.layoutWidget_19)
        self.numrange_10.setContentsMargins(0, 0, 0, 0)
        self.numrange_10.setObjectName("numrange_10")
        self.startnum_10 = QtWidgets.QLabel(self.layoutWidget_19)
        self.startnum_10.setObjectName("startnum_10")
        self.numrange_10.addWidget(self.startnum_10)
        self.tilde_10 = QtWidgets.QLabel(self.layoutWidget_19)
        self.tilde_10.setObjectName("tilde_10")
        self.numrange_10.addWidget(self.tilde_10)
        self.endnum_10 = QtWidgets.QLabel(self.layoutWidget_19)
        self.endnum_10.setObjectName("endnum_10")
        self.numrange_10.addWidget(self.endnum_10)
        self.msec_10 = QtWidgets.QLabel(self.centralwidget)
        self.msec_10.setGeometry(QtCore.QRect(890, 690, 33, 16))
        self.msec_10.setObjectName("msec_10")
        self.layoutWidget_20 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget_20.setGeometry(QtCore.QRect(930, 660, 481, 58))
        self.layoutWidget_20.setObjectName("layoutWidget_20")
        self.sliderrange_10 = QtWidgets.QVBoxLayout(self.layoutWidget_20)
        self.sliderrange_10.setContentsMargins(0, 0, 0, 0)
        self.sliderrange_10.setObjectName("sliderrange_10")
        self.starttime_10 = QtWidgets.QSlider(self.layoutWidget_20)
        self.starttime_10.setMaximum(150)
        self.starttime_10.setOrientation(QtCore.Qt.Horizontal)
        self.starttime_10.setObjectName("starttime_10")
        self.sliderrange_10.addWidget(self.starttime_10)
        self.endtime_10 = QtWidgets.QSlider(self.layoutWidget_20)
        self.endtime_10.setMaximum(150)
        self.endtime_10.setSingleStep(3)
        self.endtime_10.setPageStep(9)
        self.endtime_10.setOrientation(QtCore.Qt.Horizontal)
        self.endtime_10.setObjectName("endtime_10")
        self.sliderrange_10.addWidget(self.endtime_10)
        self.sendsirial_10 = QtWidgets.QPushButton(self.centralwidget)
        self.sendsirial_10.setGeometry(QtCore.QRect(730, 680, 91, 41))
        self.sendsirial_10.setObjectName("sendsirial_10")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1440, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.starttime_1.valueChanged['int'].connect(self.startnum_1.setNum)
        self.endtime_1.valueChanged['int'].connect(self.endnum_1.setNum)
        self.starttime_2.valueChanged['int'].connect(self.startnum_2.setNum)
        self.endtime_2.valueChanged['int'].connect(self.endnum_2.setNum)
        self.starttime_3.valueChanged['int'].connect(self.startnum_3.setNum)
        self.endtime_3.valueChanged['int'].connect(self.endnum_3.setNum)
        self.starttime_4.valueChanged['int'].connect(self.startnum_4.setNum)
        self.endtime_4.valueChanged['int'].connect(self.endnum_4.setNum)
        self.starttime_5.valueChanged['int'].connect(self.startnum_5.setNum)
        self.endtime_5.valueChanged['int'].connect(self.endnum_5.setNum)
        self.starttime_6.valueChanged['int'].connect(self.startnum_6.setNum)
        self.endtime_6.valueChanged['int'].connect(self.endnum_6.setNum)
        self.starttime_7.valueChanged['int'].connect(self.startnum_7.setNum)
        self.endtime_7.valueChanged['int'].connect(self.endnum_7.setNum)
        self.starttime_8.valueChanged['int'].connect(self.startnum_8.setNum)
        self.endtime_8.valueChanged['int'].connect(self.endnum_8.setNum)
        self.starttime_9.valueChanged['int'].connect(self.startnum_9.setNum)
        self.endtime_9.valueChanged['int'].connect(self.endnum_9.setNum)
        self.starttime_10.valueChanged['int'].connect(self.startnum_10.setNum)
        self.endtime_10.valueChanged['int'].connect(self.endnum_10.setNum)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.sendsirial_1.setText(_translate("MainWindow", "Set"))
        self.portnum_1.setText(_translate("MainWindow", "ポート1"))
        self.startnum_1.setText(_translate("MainWindow", "0"))
        self.tilde_1.setText(_translate("MainWindow", "〜"))
        self.endnum_1.setText(_translate("MainWindow", "0"))
        self.msec_1.setText(_translate("MainWindow", "msec"))
        self.sendsirial_2.setText(_translate("MainWindow", "Set"))
        self.portnum_2.setText(_translate("MainWindow", "ポート2"))
        self.startnum_2.setText(_translate("MainWindow", "0"))
        self.tilde_2.setText(_translate("MainWindow", "〜"))
        self.endnum_2.setText(_translate("MainWindow", "0"))
        self.msec_2.setText(_translate("MainWindow", "msec"))
        self.FIREbutton.setText(_translate("MainWindow", "FIRE!!!!"))
        self.portnum_3.setText(_translate("MainWindow", "ポート3"))
        self.startnum_3.setText(_translate("MainWindow", "0"))
        self.tilde_3.setText(_translate("MainWindow", "〜"))
        self.endnum_3.setText(_translate("MainWindow", "0"))
        self.msec_3.setText(_translate("MainWindow", "msec"))
        self.sendsirial_3.setText(_translate("MainWindow", "Set"))
        self.portnum_4.setText(_translate("MainWindow", "ポート4"))
        self.startnum_4.setText(_translate("MainWindow", "0"))
        self.tilde_4.setText(_translate("MainWindow", "〜"))
        self.endnum_4.setText(_translate("MainWindow", "0"))
        self.msec_4.setText(_translate("MainWindow", "msec"))
        self.sendsirial_4.setText(_translate("MainWindow", "Set"))
        self.portnum_5.setText(_translate("MainWindow", "ポート5"))
        self.startnum_5.setText(_translate("MainWindow", "0"))
        self.tilde_5.setText(_translate("MainWindow", "〜"))
        self.endnum_5.setText(_translate("MainWindow", "0"))
        self.msec_5.setText(_translate("MainWindow", "msec"))
        self.sendsirial_5.setText(_translate("MainWindow", "Set"))
        self.portnum_6.setText(_translate("MainWindow", "ポート6"))
        self.startnum_6.setText(_translate("MainWindow", "0"))
        self.tilde_6.setText(_translate("MainWindow", "〜"))
        self.endnum_6.setText(_translate("MainWindow", "0"))
        self.msec_6.setText(_translate("MainWindow", "msec"))
        self.sendsirial_6.setText(_translate("MainWindow", "Set"))
        self.portnum_7.setText(_translate("MainWindow", "ポート7"))
        self.startnum_7.setText(_translate("MainWindow", "0"))
        self.tilde_7.setText(_translate("MainWindow", "〜"))
        self.endnum_7.setText(_translate("MainWindow", "0"))
        self.msec_7.setText(_translate("MainWindow", "msec"))
        self.sendsirial_7.setText(_translate("MainWindow", "Set"))
        self.portnum_8.setText(_translate("MainWindow", "ポート8"))
        self.startnum_8.setText(_translate("MainWindow", "0"))
        self.tilde_8.setText(_translate("MainWindow", "〜"))
        self.endnum_8.setText(_translate("MainWindow", "0"))
        self.msec_8.setText(_translate("MainWindow", "msec"))
        self.sendsirial_8.setText(_translate("MainWindow", "Set"))
        self.portnum_9.setText(_translate("MainWindow", "ポート9"))
        self.startnum_9.setText(_translate("MainWindow", "0"))
        self.tilde_9.setText(_translate("MainWindow", "〜"))
        self.endnum_9.setText(_translate("MainWindow", "0"))
        self.msec_9.setText(_translate("MainWindow", "msec"))
        self.sendsirial_9.setText(_translate("MainWindow", "Set"))
        self.portnum_10.setText(_translate("MainWindow", "ポート10"))
        self.startnum_10.setText(_translate("MainWindow", "0"))
        self.tilde_10.setText(_translate("MainWindow", "〜"))
        self.endnum_10.setText(_translate("MainWindow", "0"))
        self.msec_10.setText(_translate("MainWindow", "msec"))
        self.sendsirial_10.setText(_translate("MainWindow", "Set"))
